const mongoose=require('mongoose')

const interviewSchema=new mongoose.Schema({
    userId:{type:mongoose.Schema.Types.ObjectId, ref:'User', required:true},
    role:{type:String, required:true},
    category:{type:String, default:''},
    industry:{type:String, default:''},
    jobDescription:{type:String, default:''},
    resumePath:{type:String, default:''},
    resumeName:{type:String, default:''},
 //todo STEP-1: Questions generated by Groq AI
    questions:[{type:String}],
 //todo STEP-2: Full conversation — questions + answers
    conversation:[
        {
            question:{type:String},
            answer:{type:String},
            crossQuestion:{type:String, default:null},
            crossAnswer:{type:String, default:null},
            score:{type:Number, default:0}
        }
    ],
    score:{type:Number, default:0, min:0, max:100},
    status:{type:String, enum:['in-progress', 'completed', 'abandoned'], default:'in-progress'},
},{
    timestamps:true
})

const Interview=mongoose.model('Interview', interviewSchema)
module.exports=Interview